List<String> categories = [
  "Health and beauty",
  "Phones and tablets",
  "Electronics",
  "Fashion",
  "Sporting goods",
  "Gym equipment",
  "Home and office",
  "Grocery",
  "Gifts",
  "Educational",
  "Kitchen",
  "Pets",
  "Snacks and candy",
  "Wine",
  "Liquor",
  "Meat and Seafood",
  "Small appliances",
  "Produce",
  "Pantry",
  "Beverages"
];
